name: Unit Tests

on:
  push:
    branches:
      - dev-1.0.0-pyqt5
  pull_request:
    branches:
      - dev-1.0.0-pyqt5

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update

        # Build Dependencies
        sudo apt-get install gettext sassc python3-polib

        # Application Dependencies
        sudo apt-get install python3-colorama python3-requests python3-setproctitle imagemagick
        sudo apt-get install gir1.2-gtk-3.0 gir1.2-appindicator3-0.1
        sudo apt-get install python3-pyqt5 python3-pyqt5.qtsvg python3-pyqt5.qtwebengine

    - name: Install OpenRazer Backend
      run: |
        git clone https://github.com/openrazer/openrazer --depth=1 "$GITHUB_WORKSPACE/openrazer"
        sudo add-apt-repository ppa:openrazer/daily
        sudo apt-get install openrazer-daemon python3-openrazer dbus-x11

    - name: Development Build
      run: |
        ./scripts/build-styles.sh
        ./scripts/build-locales.sh ./dist

    - name: Test Polychromatic Internals
      run: |
        ./scripts/run-unit-test.sh "10_internals"

    - name: Test OpenRazer Backend
      run: |
        eval $(sudo dbus-launch --sh-syntax)
        sudo -E ./tests/20_openrazer_daemon.sh "$GITHUB_WORKSPACE/openrazer"
